### ISSUE TITLE
No by-summoner endpoint in leagues-v3

### ISSUE THREAD

**Issue by badnatho** [cnguy/kayn#1]
Hello, as far as I can tell by the wiki, there is no by-summoner endpoint in your leagues-v3.
https://developer.riotgames.com/api-methods/#league-v3/GET_getAllLeaguesForSummoner

I'd like to use your API in a project, but I cannot until this feature is added.
(No rush)

Thanks.

**Comment by badnatho** [comment]
I assume since you only pushed the other league-v3 endpoints the other day that this is in the works.

**Comment by cnguy** [comment]
@ImNatho Oh, this is already in the library. Sorry, I still am updating the Wiki haha. I forgot to include it in the Tables of Contents, but it's actually in between the Challenger League and Master League section.

```
/lol/league/v3/leagues/by-summoner/{summonerId}
Get leagues in all queues for a given summoner ID.
getLeagues({ region, accountId/accId (int), id/summonerId/player/Id (int), name (str) }, cb)
Namespaced Functions: League.getLeagues, League.leagues, League.get
Example 1: k.League.getLeagues({ summonerId: 20026563 }, KindredAPI.print)
Example 2: k.League.get({ summonerId: 20026563 }, KindredAPI.print)
Example 3: k.League.get({ id: 20026563 }, KindredAPI.print)
Example 4: k.League.get({ name: 'Contractz' }, KindredAPI.print)
```

**Comment by cnguy** [comment]
@ImNatho Do you think the current state of documentation is fine (easy to understand, easy to move around)? I've completely updated it, but am interested in your opinion.

**Comment by badnatho** [comment]
It's pretty good. I was able to covert my existing application to kindred-api in ~40 minutes. (Over 100 endpoint implementations)
