### ISSUE TITLE
How to check if a summoner is or has been recently online?

### ISSUE THREAD

**Issue by ghost** [cnguy/kayn#17]
Hi, I know that this is not really an issue but wanted to know if there is a way to check if the summoner is playing now? I saw this website called lolnexus.com where you type the summoner and its region and they display the match list. I think that this could be achieved with the Spectator V3 endpoint but I am not so sure. Could you please give me some hint? Will appreciate it! Thanks!

**Comment by cnguy** [comment]
https://github.com/ChauTNguyen/kindred-api/wiki/SPECTATOR-V3#get-current-game-information-for-the-given-summoner-id

It is possible! That endpoint returns a 404 if a user is not in a game (data is not found). In addition, my library returns only status codes for any type of error. This means that it is easily possible to write something that does something depending on whether they're in a game or not. Here's an example:

```javascript
k.CurrentGame.get({ name: 'Contractz' }, function (err, data) {
  if (err === 404) {
    console.log('User is not in a game!')
  }
  if (data) {
    console.log('User is in a game!')
  }
})
```

**Comment by ghost** [comment]
Great! That was the thing I was looking for :) Again great info!
