### ISSUE TITLE
Add header sync and further header information

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#18]
https://puu.sh/wJDD4/b6ed675682.png

**Comment by ru-cnguyen** [comment]
https://github.com/ChauTNguyen/kindred-api/commit/e3c8f7f57f76b2c6b150d7158550cc7e148f308d

more header information in v2.0.68

**Comment by cnguy** [comment]
https://github.com/ChauTNguyen/kindred-api/commit/e3c8f7f57f76b2c6b150d7158550cc7e148f308d

Replaced LIMITS.DEV with the new dev key (keeping the old dev key as LIMITS.OLD_DEV though) and more header information here (app-rate-limit, method-rate-limit).

**Comment by cnguy** [comment]
released in 2.0.68 above (header sync still in-progress)
