### ISSUE TITLE
Add method rate-limiting

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#19]

**Comment by ru-cnguyen** [comment]
though i don't have any high-limits prod key to test this, seems like an easy change (currently half-way done)

users will be able to pass in their own method rate-limits, too
this will help in the case that Riot randomly changes rate-limits so they can quickly put on a bandaid fix

**Comment by cnguy** [comment]
https://github.com/ChauTNguyen/kindred-api/tree/feature/add-method-rate-limits

**Comment by cnguy** [comment]
releasing in v2.0.69 (https://github.com/ChauTNguyen/kindred-api/commits/rel/2.0.69)
