### ISSUE TITLE
champListData

### ISSUE THREAD

**Issue by lucasbordini** [cnguy/kayn#2]
I trying to use the static data, get List Champion and get Champion By Id 
but if I try to use the champListData: All, doesn't work 

i Trying by two ways 
```
 k.Static.champion({
        id: champId, champListData: 'all'
    })
```

and

```
const config = {
        options: {
            champData: 'all'
        }
    }
    k.Static.champions({ config }
```

is something wrong ? 
thanks

**Comment by cnguy** [comment]
### README (similar) example of what you want in the second case
```javascript
const config = {
  options: {
    champListData: 'all'
  },
  region: REGIONS.KOREA
}

k.Static.champions(config)
        .then(data => console.log(data))
        .catch(error => console.error(error))
```

### Your first example
Note that for options, my object-based functions always take in an `options` parameter. Which means you have to do:

```javascript
const options = {
   champData: 'all'
}

k.Static.champions({
  id: champId, options
})
```

### Your second example
Firstly, for a list of champions the proper parameter is ```champListData```, while for a single champion it is ```champData``` (what you want here).

Secondly, you're wrapping the config in another dictionary, which means you end up with an extra layer of brackets:

```javascript
{ // extra brackets because of { config }
  {
    options: {
      champData: 'all' // should be champListData
    }
  }
}
```

Remove the brackets around ```config```, and convert champListData -> champData and it'll work.

### Alternatives
If you'd like, you can use the methods that are more 'normal', which are documented [here](https://github.com/ChauTNguyen/kindred-api/wiki/STATIC-DATA-V3#retrieves-champion-list).

**Comment by lucasbordini** [comment]
![image](https://cloud.githubusercontent.com/assets/27768689/25807357/f319c250-33dc-11e7-8b79-8a06871e6092.png)

still without the informations of ListData

**Comment by cnguy** [comment]
@lucasbordini 

For getting the list of champions, it has to be ```champListData``` like in Riot's Docs (or my README). Yours is named ```champData``` (which is for getting a static champion by id) in the ```options```.

```javascript
const config = {
    options: {
        champListData: 'all'
    },
    region: REGIONS.BRAZIL
}

k.Static.champions(config)
    .then(data => console.log(data))
    .catch(error => console.error(error))
```

**Comment by lucasbordini** [comment]
holy, I am feeling stupid now 

sorry haha, it's works :+1:

**Comment by cnguy** [comment]
@lucasbordini 
Not your fault. I'm going to clarify how it works in the README; I removed the old explanation when I migrated my documentation to the Wiki.

In addition, I just noticed I had the wrong example in the documentation. Sorry, I thought I fixed it (in case if this was the example you used; it's the same code).

**Comment by cnguy** [comment]
@lucasbordini 

I also realized that I misread your code (sorry) when I posted my first answer. I'm editing that answer so it's correct, although it seems we have solved the issue.
