### ISSUE TITLE
How using another Region

### ISSUE THREAD

**Issue by Euphillya** [cnguy/kayn#21]
Hello, in initialization, this code is : 

`
defaultRegion: REGIONS.NORTH_AMERICA,
`

but how can i used for EUW or another ?

**Comment by Euphillya** [comment]
Ah no sorry, 

this is here => https://github.com/ChauTNguyen/kindred-api/blob/master/src/constants/regions.js

**Comment by cnguy** [comment]
@AsadaJason https://github.com/ChauTNguyen/kindred-api/wiki/Constants

This can help too. I'm thinking of fixing my documentation so everything is more clear.

note to users: kindred-api handles region->platform conversions
