### ISSUE TITLE
Setting Header Limits

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#26]
```Lets say you had 100 calls per 10 seconds, and next call you get it's down to 10 calls per 10 seconds. ```

Not sure how I'd do this cleanly (though Kindred already is pretty unclean).

**Comment by Colorfulstan** [comment]
I think you're referring to the discord discussion.
My conclusion from that is:
don't update the request-counts from the headers, just make sure you back off on 429's acchordingly.

If the limit suddenly changes, just update the limit and the next check for available requests should say: "nope" until the interval is resetting.

Avoiding 429s all together is an Illusion when trying to maximise the requests done near the limit-edges, that's my take from the Discord talk earlier.
