### ISSUE TITLE
Kayn TS Typings

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#33]
:)

**Comment by cnguy** [comment]
Released the basic TypeScript-superpowered API in 0.2.5.

However, I left a lot of the returned interfaces as `any` for now. This will be fixed over time as this is kind of a pain in the ass.

**Comment by Colorfulstan** [comment]
Let me throw this in here
https://github.com/Protectator/league-typedef

**Comment by cnguy** [comment]
https://github.com/cnguy/kayn/tree/use-mingwei-swagger

gonna try out swagger generated typings

**Comment by cnguy** [comment]
all DTOs have been added as of v0.8.0
