### ISSUE TITLE
Caching interface should be improved

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#36]
Not everyone wants to type out all the methods they want to cache...

Some people might want to cache the entire static service
Some people might want to cache specific method ttls.

**Comment by cnguy** [comment]
This is high-priority now.
Still TBD (+ I haven't got good sleep for the past few days so this might be worded badly) but this is a high-level overview..

Firstly, a `useDefault` cache options property will be added. By default, it will be set to `false`.

This will allow users to:
* still have fine-grained control over specific method caching with existing `ttls` object property
* use the default caching object (if Riot has one we'll use that) while still being able to override specific ttls
* not make existing users cache random stuffs when upgrading (backwards-compatible pls)

The caching priority will be:
1) any (method name, ttl in milliseconds) pair in  `ttls` will override everything else (so for now, just the default ttl object) **because it is the most specific way of setting a ttl**
2) setting by Endpoint groups (as per Riot Docs)
3) any default ttl that has not been overrided

So the `cache` and `ttls` properties will function the same. Any specific `ttl` key-value pair will override the specific key-value pair in the default.

For example...
Let's say the Summoner.by.name() is cached for `1 day` by default, but we decide to set the Summoner.by.name METHOD_NAMES pair to 3000 ms within `ttls`.
```javascript
Kayn()({
    cacheOptions: {
        cache: BasicJSCache() or RedisCache or whatever,
        useDefault: true,
        groupTTLs: {
            'STATIC': 30000,
        },
        ttls: {
            [METHOD_NAMES.SUMMONER.GET_BY_SUMMONER_NAME]: 3000 //ms 
        }
    },
})
```

Initially, the cache timer for Summoner.by.name would be 1 day (in milliseconds) since `useDefault` is turned on. However, since we have the `ttls` property with the specific key-value pair, the cache timer is now 3 seconds (in milliseconds).

**Comment by SeaRoth** [comment]
How far are you? I'm going to put in some hours today learning RedisCache and figure out how to cache the matches on the server - I'll share the code with the community if I figure it out.

**Comment by cnguy** [comment]
I can probably finish a basic implementation of everything mentioned in the post, along with tests, on Wednesday. It's pretty much just merging objects.

I'll probably also make a small website that allows you to just input TTLs, and it will format the JSON for you automatically.

**Comment by SeaRoth** [comment]
That's really cool man - I just made my first redis server lol. Thank you for this, btw, and you should consider adding your BTC address to the bottom of your README if you're not already too rich xD
