### ISSUE TITLE
Support optional count query param

### ISSUE THREAD

**Issue by OllieJennings** [cnguy/kayn#50]
https://github.com/cnguy/kayn/blob/4e6d0fa3a4385d2a00ccd87d00f5a158d160c84b/lib/Endpoints/TournamentStubEndpoint.js#L39

Tournament Stub endpoint allows you to create a number of tournament codes (upto 1000 Max)

This is also the same with the main tournament API

https://github.com/cnguy/kayn/blob/4e6d0fa3a4385d2a00ccd87d00f5a158d160c84b/lib/Endpoints/TournamentEndpoint.js#L41

**Comment by OllieJennings** [comment]
Just realised this is probably supported via `.query({ count: <Int> })`?

**Comment by cnguy** [comment]
yes, tournament id is the only one mandatory so that is why it is already in the code @OllieJennings

**Comment by OllieJennings** [comment]
Cheers
