### ISSUE TITLE
TS1005 Error

### ISSUE THREAD

**Issue by Scotsoo** [cnguy/kayn#51]
error  in c:\....\node_modules\kindred-api\typings\index.d.ts

[tsl] ERROR in c:\....\node_modules\kindred-api\typings\index.d.ts(365,27)
      TS1005: '(' expected.

I'm running nuxtjs and only accessing the kindred-api library from the backend. I'll fork and raise a PR for the fix

**Comment by Scotsoo** [comment]
This is from latest NPM build in kindred-api

**Comment by Scotsoo** [comment]
Ignore this, I'll pull kayn instead of kindred-api. Didn't realise it was it's replacement.

**Comment by cnguy** [comment]
lmk if it's fine

**Comment by Scotsoo** [comment]
Yeah sorry dude, was using the old kindred-api on npm. Upgraded to kayn now. Can close this
