### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#55]
https://discussion.developer.riotgames.com/articles/6579/player-universally-unique-identifiers-and-a-new-se.html

Scheduled Deprecation Date: January 14th, 2019

Going to start early and going to separate V4 endpoints from the regular endpoints for now until I think of better ideas.,

Summoner
SummonerV4

I'll release some deprecation warnings later on tomorrow as well. Once the endpoints are actually removed, I can replace the regular endpoints with the V4 ones.

SummonerV4 => Summoner, while SummonerV4 will still work

Checklist:
- [x] CHAMPION MASTERIES V4
- [x] LEAGUE V4
- [x] MATCH V4
- [X] SPECTATOR V4
- [x] SUMMONER V4
- [x] THIRD PARTY CODE V4
- [x] TOURNAMENT STUB V4
- [x] TOURNAMENT V4
- [x] TS Bindings
- [x] Release
- [x] Change deprecation date to January 28th (as noted on Riot API docs)

**Comment by cnguy** [comment]
v4 endpoints are currently down, FeelsBadMan

edit: november 20, don't think the deadline is going to extend to compensate too, never lucky

**Comment by cnguy** [comment]
Riot should be re-releasing the V4 endpoints beginning of next week!

**Comment by cnguy** [comment]
v4 by Riot is now released so dev work will be resumed. Added checklist

**Comment by cnguy** [comment]
I have one last finals on Friday and I can continue :)

**Comment by cnguy** [comment]
I'll be releasing v0.9.0 today! See https://github.com/cnguy/kayn/blob/d8143809cad5228c66ac3ae81bf10584f5d099d1/CHANGELOG.md for changes.

Feel free to post any comments and/or concerns here!

**Comment by Ilshidur** [comment]
I just migrated to V4 thanks to your changes. Worked like a charm !

Thanks for your work :+1:

**Comment by cnguy** [comment]
awesome! I still need to migrate my stuffs too
