### ISSUE TITLE
Minor unnecessary import in index.d.ts

### ISSUE THREAD

**Issue by cnguy** [cnguy/kayn#70]
```
node_modules/kayn/typings/index.d.ts:2:28 - error TS7016: Could not find a declaration file for module '../lib/RequestClient/DDragonRequest'. '.../node_modules/kayn/lib/RequestClient/DDragonRequest.js' implicitly has an 'any' type.

import DDragonRequest from '../lib/RequestClient/DDragonRequest'
```

Will be fixed in v0.9.11.

**Comment by cnguy** [comment]
Fixed & released.

**Comment by raitono** [comment]
This line was from my PR back when I added the initial typings in  #67.

Looks like there was some refactoring done and that line was left hanging around in commit fb8694115f36df8608c4688f953a9f90f4a7f460.

I was just looking around because I was scared I had broken something.

**Comment by cnguy** [comment]
Thanks for notifying me, it's no problem. Thought it was my VSCode since VSCode is eager to import things. I refactored it slightly so now we get the .locale/.version types. If you're still using the library, have your `any` errors disappeared?

**Comment by raitono** [comment]
Real life caught up with me and I haven't had the opportunity to do any hobby coding lately so I won't be able to try it out, sorry!

**Comment by cnguy** [comment]
No problem! Good luck :)
